### ISSUE TITLE
How to know what app is new

### ISSUE THREAD

**Issue by kevinsawicki** [electron/electron.atom.io#662] opened 2017-01-26 00:26 UTC
>Hello, I would like to know how I can identify which applications are new or recently released, since with the new system everything is in order, and not as before every application that was new, was at the end.

Moved over from https://github.com/electron/electron/issues/8506

/cc @PterPmnta

**Comment by zeke** [comment] 2017-01-30 17:44
Good point. We will figure something out.

This sounds like a duplicate of #661, so I'm gonna close it.

**Closed by zeke** 2017-01-30 17:44 UTC
Labels: enhancement

**Comment by PterPmnta** [comment] 2017-01-30 23:14
@zeke ok, when release this solution?

**Comment by zeke** [comment] 2017-01-30 23:29
@PterPmnta I don't have a specific time for you, but given the number of reactions on #661 I can see that it's important, so we will prioritize it. Please watch this issue for updates.
